{% set name = "django-autocomplete-light" %}
{% set version = "3.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-autocomplete-light-{{ version }}.tar.gz
  sha256: a34f192ac438c4df056dbfd399550799ddc631c4661960134ded924648770373

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=3.2
    - six

test:
  imports:
    - dal
    - dal_contenttypes
    - dal_genericm2m
    - dal_genericm2m_queryset_sequence
    - dal_gm2m
    - dal_gm2m_queryset_sequence
    - dal_legacy_static
    - dal_queryset_sequence
    - dal_select2
    - dal_select2_queryset_sequence
    - dal_select2_tagging
    - dal_select2_taggit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-autocomplete-light.rtfd.org
  summary: Fresh autocompletes for Django
  dev_url: https://github.com/yourlabs/django-autocomplete-light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
